version: '3'

services:
  app:
    build: ./frontend
    ports:
      - 80:5173
    volumes:
      - ./frontend/src:/app/src
  api: 
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongobd//bd/gamify
    volumes:
      - ./backend/:/app
    depends_on:
      - db
  api-test: 
    image: app-api
    environment:
      - DB_URL=mongobd//bd/gamify-tests
    volumes:
      - ./backend/:/app
      - ./backend/:/tests
    depends_on:
      - db
    command: npm test
  db:
    image: mongo:5.0.19-focal
    ports:
      - 27017:27017
    volumes:
      - gamify:/data/db
volumes:
  gamify: 